name: Get full info
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: npx --yes tsx generate-full-info.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-info.json
          path: ./full-info.json
